// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemEvents.proto

package etf.pnwt.grpc;
public interface SystemEventsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SystemEventsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
